version: '3'

services:
  backend:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - ollama

  frontend:
    build: .
    command: python gui.py
    ports:
      - "8001:8001"
    depends_on:
      - backend

  ollama:
    image: ghcr.io/jmorganca/ollama:latest
    ports:
      - "11434:11434"
