version: '3'

services:
  app:
    build: .
    #command: python main.py
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
